redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
        - ./data/redis:/data
    ports:
       - 6379:6379 

web:
    build: .
    volumes:
        - .:/app
    ports:
        - 8080:8080
    links:
        - redis
